// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUstsfMWMR6S7s9EkOE6u8nc_Io_1oK2Y',
    appId: '1:785788554769:web:78d3c97e4cf45fcc292bb0',
    messagingSenderId: '785788554769',
    projectId: 'irhebo-63e09',
    authDomain: 'irhebo-63e09.firebaseapp.com',
    storageBucket: 'irhebo-63e09.firebasestorage.app',
    measurementId: 'G-7CRB7Y6QHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjlRfStnNlTr8LtA7WLuUUlJiEXzhwyzk',
    appId: '1:785788554769:android:799eea404dbaffa9292bb0',
    messagingSenderId: '785788554769',
    projectId: 'irhebo-63e09',
    storageBucket: 'irhebo-63e09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6bdiao_hIkSgg9DHxyJHxmJOVZE1WuKw',
    appId: '1:785788554769:ios:29da10d75e666ac5292bb0',
    messagingSenderId: '785788554769',
    projectId: 'irhebo-63e09',
    storageBucket: 'irhebo-63e09.firebasestorage.app',
    iosBundleId: 'com.ptplatform.irhebo',
  );

}
